### ISSUE TITLE
fmgr_task_task_obj is missing from v2.0.0

### ISSUE THREAD

**Issue by mbdraks** [fortinet-ansible-dev/ansible-galaxy-fortimanager-collection#10]
Hi,

Module fmgr_task_task_obj no longer exist. Is there any alternative?

For reference, this is the module: https://github.com/fortinet-ansible-dev/ansible-galaxy-fortimanager-collection/blob/galaxy/1.0.5/plugins/modules/fmgr_task_task_obj.py

**Comment by chillancezen** [comment]
hi @mbdraks Michel,
2.0.0 has broken compatibility.
since 2.0.0, any APIs request with `GET` methods are all in module `fmgr_fact`.
https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/galaxy-2.0.0/fact.html

please see notes:  https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/galaxy-2.0.0/fmgr_fact.html#notes
and example:https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/galaxy-2.0.0/fmgr_fact.html#examples


for task, the selector is `task_task `,
here is an example to query task:
https://raw.githubusercontent.com/fortinet-ansible-dev/fortimanager-playbook-example/2.0.0/output/discover_and_add_device.yml


btw, you can search runnable playbooks in page: https://ansible-galaxy-fortimanager-docs.readthedocs.io/en/galaxy-2.0.0/example.html

please let me know if you have any issues.

thanks.
Link.

**Comment by mbdraks** [comment]
Great! I was searching on the wrong page (modules).

Tks and have a nice weekend!
